name: Build and publish

on: 
  [push, workflow_dispatch]

jobs:
  build_pages:
    name: Publish Edition as GitHub Pages Website
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Install Java and Ant
      run: |
        sudo apt-get update && sudo apt-get install openjdk-11-jre-headless ant -y
    - name: Install Saxon
      run: shellscripts/script.sh
    - name: Install Python dependencies
      run: pip install -r requirements.txt
    - name: Fetch data
      run: ./shellscripts/fetch_data.sh
    - name: Build
      run: |
        ant
    - name: Update Favicons
      run: pyscripts/update_favicons.py
    - name: Update Translations
      run: pyscripts/make_translations.py
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./html
